bestie: Fix build under ubuntu
When building under ubuntu 18.04, I get the following error:

```
In file included from /usr/include/fcntl.h:290:0,
                 from cp.c:6:
In function ‘open’,
    inlined from ‘copyfile’ at cp.c:52:5:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
    __open_missing_mode ();
    ^~~~~~~~~~~~~~~~~~~~~~
```

According to
https://wiki.ubuntu.com/ToolChain/CompilerFlags?action=show&redirect=CompilerFlags#A-D_FORTIFY_SOURCE.3D2
In ubuntu, gcc runs with -D_FORTIFY_SOURCE=2 by default which requires that
the mode argument is passed to open if O_CREAT is passed in the flags.

Change-Id: I3b37d355152f1c7e3d617e50d1b5412cf38938d9